import {
  Injectable,
  NotFoundException,
  InternalServerErrorException,
} from '@nestjs/common';
import { SupabaseService } from '../../supabase/supabase.service';
import { CreateLeadDto } from './dto/create-lead.dto';
import { UpdateLeadDto } from './dto/update-lead.dto';
import { LeadFilterDto } from './dto/lead-filter.dto';
import { LeadStatus } from '../../types';

@Injectable()
export class LeadsService {
  constructor(private readonly supabase: SupabaseService) {}

  async create(brandId: string, createLeadDto: CreateLeadDto) {
    const client = this.supabase.getClient();

    // Calculate SLA deadline (5 mins from now)
    const slaDeadline = new Date();
    slaDeadline.setMinutes(slaDeadline.getMinutes() + 5);

    // display_id will be auto-generated by the Postgres trigger
    const { data, error } = await client
      .from('leads')
      .insert([
        {
          ...createLeadDto,
          brand_id: brandId,
          sla_deadline: slaDeadline.toISOString(),
        },
      ])
      .select()
      .single();

    if (error) {
      throw new InternalServerErrorException(error.message);
    }

    return data;
  }

  async findAll(brandId: string, filterDto: LeadFilterDto) {
    const client = this.supabase.getClient();
    let query = client
      .from('leads')
      .select('*, customer:customers(*)', { count: 'exact' })
      .eq('brand_id', brandId);

    if (filterDto.status) {
      query = query.eq('status', filterDto.status);
    }
    if (filterDto.priority) {
      query = query.eq('priority', filterDto.priority);
    }
    if (filterDto.assigned_sdr_id) {
      query = query.eq('assigned_sdr_id', filterDto.assigned_sdr_id);
    }

    const page = filterDto.page || 1;
    const limit = filterDto.limit || 10;
    const from = (page - 1) * limit;
    const to = from + limit - 1;

    query = query.range(from, to).order('created_at', { ascending: false });

    const { data, error, count } = await query;

    if (error) {
      throw new InternalServerErrorException(error.message);
    }

    // Attach SLA computed status
    const now = new Date();
    const leadsWithSla = data.map((lead) => {
      let slaStatus = 'normal';
      if (lead.sla_deadline && lead.status === LeadStatus.New) {
        const deadline = new Date(lead.sla_deadline);
        const timeDiffMs = deadline.getTime() - now.getTime();

        if (timeDiffMs < 0) {
          slaStatus = 'critical';
        } else if (timeDiffMs < 2 * 60 * 1000) {
          // less than 2 mins
          slaStatus = 'warning';
        }
      }
      return { ...lead, sla_status: slaStatus };
    });

    return {
      data: leadsWithSla,
      meta: {
        total: count,
        page,
        limit,
        totalPages: Math.ceil((count || 0) / limit),
      },
    };
  }

  async findOne(brandId: string, id: string) {
    const client = this.supabase.getClient();

    const { data, error } = await client
      .from('leads')
      .select(
        `
        *,
        customer:customers(*),
        quotes(id, display_id, status, total)
      `,
      )
      .eq('id', id)
      .eq('brand_id', brandId)
      .single();

    if (error) {
      throw new NotFoundException(`Lead with ID ${id} not found`);
    }

    return data;
  }

  async update(brandId: string, id: string, updateLeadDto: UpdateLeadDto) {
    const client = this.supabase.getClient();

    const { data, error } = await client
      .from('leads')
      .update({
        ...updateLeadDto,
        updated_at: new Date().toISOString(),
      })
      .eq('id', id)
      .eq('brand_id', brandId)
      .select()
      .single();

    if (error) {
      throw new InternalServerErrorException(error.message);
    }

    if (!data) {
      throw new NotFoundException(`Lead with ID ${id} not found`);
    }

    return data;
  }

  async assign(brandId: string, id: string, sdrId: string) {
    return this.update(brandId, id, { assigned_sdr_id: sdrId });
  }

  async convertToQuote(brandId: string, id: string) {
    const client = this.supabase.getClient();

    // 1. Fetch the lead to get customer_id and other details
    const lead = await this.findOne(brandId, id);
    if (!lead) {
      throw new NotFoundException(`Lead with ID ${id} not found`);
    }

    // 2. Create a new Draft quote for this lead/customer
    const { data: quote, error: quoteErr } = await client
      .from('quotes')
      .insert([
        {
          brand_id: brandId,
          customer_id: lead.customer_id,
          lead_id: lead.id,
          status: 'Draft',
          subtotal: 0,
          tax: 0,
          total: 0,
          valid_until: new Date(
            Date.now() + 30 * 24 * 60 * 60 * 1000,
          ).toISOString(), // 30 days
        },
      ])
      .select()
      .single();

    if (quoteErr) {
      throw new InternalServerErrorException(
        `Failed to create quote: ${quoteErr.message}`,
      );
    }

    // 3. Update the lead status to Won
    const updatedLead = await this.update(brandId, id, {
      status: LeadStatus.Won,
    });

    return { lead: updatedLead, quote };
  }

  async getOverdue(brandId: string) {
    const client = this.supabase.getClient();
    const now = new Date().toISOString();

    const { data, error } = await client
      .from('leads')
      .select('*')
      .eq('brand_id', brandId)
      .eq('status', LeadStatus.New)
      .lt('sla_deadline', now);

    if (error) {
      throw new InternalServerErrorException(error.message);
    }

    return data;
  }

  async getNextAvailableSdr(brandId: string) {
    const client = this.supabase.getClient();

    // We want to find the SDR with the fewest active leads.
    // Since we can't do complex grouping easily with postgREST,
    // we'll fetch SDR profiles and then count. A postgres RPC is better here.
    const { data, error } = await client.rpc('get_next_available_sdr', {
      p_brand_id: brandId,
    });

    if (error) {
      throw new InternalServerErrorException(error.message);
    }

    return data;
  }
}
